### ISSUE TITLE
Error when calling two run functions in a row

### ISSUE THREAD

**Issue by irevenko** [hajimehoshi/oto#135]
When i'm trying to run the example code https://github.com/hajimehoshi/oto/blob/master/example/main.go
I just want to execute ```run``` function multiple times. What am i doing wrong?

```go
func main() {
	if err := run(); err != nil {
		panic(err)
	}

	if err := run(); err != nil {
		panic(err)
	}
}
```

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b4f pc=0x7f4bfb8180fa]

runtime stack:
runtime.throw(0x4e54b0, 0x2a)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 18 [syscall]:
runtime.cgocall(0x4b4d60, 0xc000049e70, 0xc000049e00)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000049e40 sp=0xc000049e08 pc=0x4059db
github.com/hajimehoshi/oto._Cfunc_snd_pcm_drop(0x1b13460, 0xc000000000)
        _cgo_gotypes.go:134 +0x49 fp=0xc000049e70 sp=0xc000049e40 pc=0x4b2809
github.com/hajimehoshi/oto.(*driver).Close.func1(0xc000060100, 0xc0000c4000)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:177 +0x59 fp=0xc000049ea8 sp=0xc000049e70 pc=0x4b3c19
github.com/hajimehoshi/oto.(*driver).Close(0xc000060100, 0x4e7000, 0x1)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:177 +0x2f fp=0xc000049ed0 sp=0xc000049ea8 pc=0x4b354f
github.com/hajimehoshi/oto.(*driverWriter).Close(0xc000182000, 0x0, 0x0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:170 +0xb5 fp=0xc000049f18 sp=0xc000049ed0 pc=0x4b1d95
github.com/hajimehoshi/oto.(*Context).Close(0xc00018a000, 0xc000182000, 0x500780)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:106 +0x7b fp=0xc000049f68 sp=0xc000049f18 pc=0x4b181b
github.com/hajimehoshi/oto.NewContext.func1(0xc00018a000)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:89 +0xa5 fp=0xc000049fd8 sp=0xc000049f68 pc=0x4b36a5
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000049fe0 sp=0xc000049fd8 pc=0x468b21
created by github.com/hajimehoshi/oto.NewContext
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:84 +0x269

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000020238)
        /usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000020230)
        /usr/local/go/src/sync/waitgroup.go:130 +0x65
main.run(0x0, 0x0)
        /home/irevenko/Code/qwe/main.go:131 +0xf3
main.main()
        /home/irevenko/Code/qwe/main.go:141 +0x3b

goroutine 6 [syscall]:
github.com/hajimehoshi/oto._Cfunc_snd_pcm_writei(0x1b13cc0, 0xc000130e00, 0x155, 0x0)
        _cgo_gotypes.go:176 +0x4e
github.com/hajimehoshi/oto.(*driver).TryWrite.func1(0xc000060140, 0xc0000b4000)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:158 +0xda
github.com/hajimehoshi/oto.(*driver).TryWrite(0xc000060140, 0xc0000b404c, 0xb4, 0x8000, 0x4c61c0, 0xc0000761b0, 0xc000078dd0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/driver_linux.go:158 +0x1d8
github.com/hajimehoshi/oto.(*driverWriter).Write(0xc000076180, 0xc0000b4000, 0x100, 0x8000, 0x0, 0x0, 0x0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:144 +0x11f
io.copyBuffer(0x500760, 0xc000076180, 0x500780, 0xc000060180, 0xc0000b4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:411 +0x206
io.Copy(...)
        /usr/local/go/src/io/io.go:368
github.com/hajimehoshi/oto.NewContext.func1(0xc00000fc00)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:85 +0x69
created by github.com/hajimehoshi/oto.NewContext
        /home/irevenko/go/src/github.com/hajimehoshi/oto/context.go:84 +0x269

goroutine 7 [select]:
io.(*pipe).Write(0xc000062240, 0xc000122600, 0x5a00, 0x5a00, 0x2600, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:94 +0x1e5
io.(*PipeWriter).Write(0xc000010030, 0xc000120000, 0x8000, 0x8000, 0x4, 0x30, 0xc00003ce78)
        /usr/local/go/src/io/pipe.go:163 +0x4c
github.com/hajimehoshi/oto.(*Player).Write(0xc0000761e0, 0xc000120000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /home/irevenko/go/src/github.com/hajimehoshi/oto/player.go:66 +0x96
io.copyBuffer(0x500740, 0xc0000761e0, 0x5007e0, 0xc000076210, 0xc000120000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:411 +0x206
io.Copy(...)
        /usr/local/go/src/io/io.go:368
main.play(0xc00000fc00, 0x4085e00000000000, 0x3b9aca00, 0x0, 0x0)
        /home/irevenko/Code/qwe/main.go:102 +0x125
main.run.func1(0xc000020230, 0xc00000fc00)
        /home/irevenko/Code/qwe/main.go:126 +0x6e
created by main.run
        /home/irevenko/Code/qwe/main.go:124 +0xe5
exit status 2
```

**Comment by irevenko** [comment]
Figured it out.
It was ```oto library``` problem, i just need to create a context and player outside of ```play``` function

```go
package main

import (
	"io/ioutil"
	"log"
	"time"

	"github.com/hajimehoshi/oto"
	"github.com/tosone/minimp3"
)

func read() (decoder *minimp3.Decoder, audioData []byte) {
	file, err := ioutil.ReadFile("beep-07.mp3")
	if err != nil {
		log.Fatal(file)
	}

	var dec *minimp3.Decoder
	var data []byte
	dec, data, _ = minimp3.DecodeFull(file)

	return dec, data
}

func play(data []byte, dec *minimp3.Decoder, p *oto.Player) {
	p.Write(data)

	<-time.After(time.Second)

	dec.Close()
}

func main() {
	decoder, data := read()

	var context *oto.Context
	context, _= oto.NewContext(decoder.SampleRate, decoder.Channels, 2, 1024)
	player := context.NewPlayer()


	play(data, decoder, player)
	play(data, decoder, player)
}
```
